# Generated by Django 4.2.3 on 2023-07-08 02:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("perfil", "0001_initial"),
        ("extrato", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Valor",
            new_name="Extrato",
        ),
    ]
